version: '3'

networks:
  react:

services:
  react-app:
    image: node:alpine
    ports:
      - 3000:3000
    volumes:
      - ./app-src:/react-app
    working_dir: /react-app
    stdin_open: true
    entrypoint: ['npm', 'start']
    networks:
      - react

  init:
    image: node:alpine
    volumes:
      - ./app-src:/react-app
    working_dir: /
    stdin_open: true
    entrypoint: ['npx', 'create-react-app', 'react-app']
    networks:
      - react

  npm:
    image: node:alpine
    volumes:
      - ./app-src:/react-app
    working_dir: /react-app
    stdin_open: true
    entrypoint: ['npm']
    networks:
      - react

  npx:
    image: node:alpine
    volumes:
      - ./app-src:/react-app
    working_dir: /react-app
    stdin_open: true
    entrypoint: ['npx']
    networks:
      - react