version: '3'

networks:
  react:

services:
  react-app:
    image: node:alpine
    ports:
      - 3000:3000
    volumes:
      - ./app-src:/react-app
    working_dir: /react-app
    stdin_open: true
    entrypoint: [ 'npm', 'run', 'dev' ]
    networks:
      - react

  prod:
    image: node:alpine
    ports:
      - 80:3000
    volumes:
      - ./app-src:/react-app
    working_dir: /react-app
    stdin_open: true
    command: "sh -c 'npm run build && npm start;'"
    networks:
      - react

  init:
    image: node:alpine
    volumes:
      - ./app-src:/react-app
    working_dir: /
    stdin_open: true
    entrypoint: [ 'npx', 'create-next-app@latest', 'react-app' ]
    networks:
      - react

  init-next:
    image: node:alpine
    volumes:
      - ./app-src:/react-app
    working_dir: /
    stdin_open: true
    entrypoint:
      [
        'npx',
        'create-next-app@latest',
        'react-app',
        '--typescript'
      ]
    networks:
      - react

  npm:
    image: node:alpine
    volumes:
      - ./app-src:/react-app
    working_dir: /react-app
    stdin_open: true
    entrypoint: [ 'npm' ]
    networks:
      - react

  frontend-web:
    image: node:latest
    ports:
      - 3000:3000
    volumes:
      - ./app-src:/react-app
    working_dir: /react-app
    stdin_open: true
    command: "sh -c 'npm run build && npx serve -s build -l 3000;'"
    networks:
      - react

  npx:
    image: node:alpine
    volumes:
      - ./app-src:/react-app
    working_dir: /react-app
    stdin_open: true
    entrypoint: [ 'npx' ]
    networks:
      - react
